version: v0.13.0

dsn: postgres://user:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4

serve:
  public:
    base_url: https://auth.domain.com/ 
    cors:
      enabled: true
      allowed_origins:
        - https://domain.com
        - https://*.domain.com
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Cookie
        - Content-Type
      exposed_headers:
        - Content-Type
        - Set-Cookie
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: https://auth.domain.com/auth/
  allowed_return_urls:
    - https://auth.domain.com/auth/

  methods:
    password:
      enabled: true
    totp:
      config:
        issuer: domain.com
      enabled: true
    lookup_secret:
      enabled: false 
    link:
      enabled: true
    code:
      enabled: true

  flows:
    error:
      ui_url: https://auth.domain.com/auth/error

    settings:
      ui_url: https://auth.domain.com/auth/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: https://auth.domain.com/auth/recovery
      use: code

    verification:
      enabled: true
      ui_url: https://auth.domain.com/auth/verification
      use: code
      after:
        default_browser_return_url: https://auth.domain.com/auth

    logout:
      after:
        default_browser_return_url: https://auth.domain.com/auth/login

    login:
      ui_url: https://auth.domain.com/auth/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: https://auth.domain.com/auth/registration
      after:
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 12

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

session:
  cookie:
    name: session
    domain: domain.com
    path: /
    same_site: Strict
 
courier:
  message_retries: 5 
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
    from_address: no-reply@domain.com
    from_name: support
  templates:
    recovery_code:
      valid:
        email:
          subject: file:///templates/recovery_code/valid/email.subject.gotmpl
          body: 
            html: file:///templates/recovery_code/valid/email.body.gotmpl
            plaintext: file:///templates/recovery_code/valid/email.body.plaintext.gotmpl
      invalid:
        email:
          subject: file:///templates/recovery_code/invalid/email.subject.gotmpl
          body: 
            html: file:///templates/recovery_code/invalid/email.body.gotmpl
            plaintext: file:///templates/recovery_code/invalid/email.body.plaintext.gotmpl
    verification:
      valid:
        email:
          subject: file:///templates/verification/valid/email.subject.gotmpl
          body: 
            html: file:///templates/verification/valid/email.body.gotmpl
            plaintext: file:///templates/verification/valid/email.body.plaintext.gotmpl
      invalid:   
        email:
          subject: file:///templates/verification/invalid/email.subject.gotmpl
          body: 
            html: file:///templates/verification/invalid/email.body.gotmpl
            plaintext: file:///templates/verification/invalid/email.body.plaintext.gotmpl
    verification_code:
      valid:
        email:
          subject: file:///templates/verification_code/valid/email.subject.gotmpl
          body: 
            html: file:///templates/verification_code/valid/email.body.gotmpl
            plaintext: file:///templates/verification_code/valid/email.body.plaintext.gotmpl
      invalid:
        email:
          subject: file:///templates/verification_code/invalid/email.subject.gotmpl
          body: 
            html: file:///templates/verification_code/invalid/email.body.gotmpl
            plaintext: file:///templates/verification_code/invalid/email.body.plaintext.gotmpl
    recovery:
      valid:
        email:
          subject: file:///templates/recovery/valid/email.subject.gotmpl
          body: 
            html: file:///templates/recovery/valid/email.body.gotmpl
            plaintext: file:///templates/recovery/valid/email.body.plaintext.gotmpl
      invalid:
        email:
          subject: file:///templates/recovery/invalid/email.subject.gotmpl
          body: 
            html: file:///templates/recovery/invalid/email.body.gotmpl
            plaintext: file:///templates/recovery/invalid/email.body.plaintext.gotmpl
      
tracing:
  service_name: Ory Kratos
  providers:
    zipkin:
      sampling:
        sampling_ratio: 0.4
      server_url: http://zipkin:9411/api/v2/spans 
  provider: zipkin

log:
  leak_sensitive_values: false
  redaction_text: ""
  format: json
  level: trace
